"""empty message

Revision ID: 8ebb1160fadc
Revises: 6ea540dfeb13
Create Date: 2020-05-25 11:49:07.420499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ebb1160fadc'
down_revision = '6ea540dfeb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teammates', sa.Column('linkedin', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'teammates', ['role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teammates', type_='unique')
    op.drop_column('teammates', 'linkedin')
    # ### end Alembic commands ###
